### ISSUE TITLE
Running integration tests with CI service

### ISSUE THREAD

**Issue by HakkyuKim** [flutter-tizen/plugins#148]
I tried several ways to run emulators in CI server for integration tests but concluded that it just cannot be done without digging into how Tizen emulators work under the hood. I did manage to run the emulator, but sdb can't find it: https://cirrus-ci.com/task/5968653813284864 (test branch: https://github.com/HakkyuKim/plugins/tree/cirrus).

Look for:

```sh
em-cli launch --name flutter_emulator
Launch command : "/home/tizen/tizen-studio/platforms/tizen-4.0/common/emulator/bin/emulator.sh" --conf "/home/tizen/tizen-studio-data/emulator/vms/flutter_emulator/vm_launch.conf" -j "/home/tizen/tizen-studio/jdk/bin/java"
The VM is launched
...

sdb devices
List of devices attached 

```

So instead, I'm considering running integration tests on our machine that's connected to physical targets using Azure Pipelines [self-hosted agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#install).

There are a few considerations:

- Corporate policy regarding network security (I'll start asking around next week)
- Pricing
    According to [pricing for Azure DevOps](https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/), we need at minimum "User License: Basic Plan", which is free for the first 5 users.
- Cost of maintenance 
    The host machine and the Tizen devices attached to it.

Personally I think it's the best option to do CI for plugin integration tests and possibly future engine regression tests. Please share any ideas or suggestions.

TODOs:

- [x] write test tool script (reference: [flutter-plugin-tools](https://github.com/flutter/plugins/tree/master/script/tool)) #150 
- [x] fix broken integration tests or exclude them in CI task: video_players, integration_test, etc #169 #182 
- [x] write ~~azure pipelines~~github workflow script #169 
- [x] think about how to let the tool know about unsupported device profiles of each plugin https://github.com/flutter-tizen/plugins/pull/191

**Comment by swift-kim** [comment]
Regarding the pricing, we don't need to buy user licenses. We just need to add a self-hosted agent which costs $15 per month.

![image](https://user-images.githubusercontent.com/40190588/125051322-cd330800-e0dd-11eb-916d-e15ade4638b4.png)

**Comment by HakkyuKim** [comment]
Using two self hosts is because one is being used by the engine repo right? Then yes $15 per month. 

I thought 5 users meant 5 accounts can be in invited in the Azure organization but I guess its something else.

**Comment by HakkyuKim** [comment]
Pull requests will now trigger integration tests through internal server(self-hosted runner). Currently only a single self-hosted runner performs testing on wearable-5.5 emulator for all pull requests. The number of runners and testing platforms(device profiles) will be improved sometime next week. In the meantime, we may check how the system performs in our current development process.
