### ISSUE TITLE
[permission_handler] Remaining issues

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#61]
- [x] Tizen 4.0 support → #139
- [x] `openAppSettings()` returns false on some devices (APP_NOT_FOUND) → https://github.com/flutter-tizen/plugins/issues/61#issuecomment-872772385
- [x] `openAppSettings()` opens the system settings but not the app settings → #142
- [x] Replace `ErrorToString` with the built-in `get_error_message` function → #111

**Comment by bbrto21** [comment]
> openAppSettings() always returns false (APP_NOT_FOUND)

It seems to work fine on mobile. could you tell me details?

**Comment by swift-kim** [comment]
@bbrto21 Does it? I had only tested on watch devices.

**Comment by bbrto21** [comment]
on tw3 binary I got a below error, but on R840, it is fine too
```
E/CAPI_APPFW_APP_CONTROL( 4667): app_control.c: app_control_error(438) > [__launch_request_send] APP_NOT_FOUND(0xfef00021)

```

**Comment by bbrto21** [comment]
> W/AUL     ( 4667): launch.c: app_request_to_launchpad_for_uid(266) > request cmd(0) result : -13

I guess it means permission denied

**Comment by swift-kim** [comment]
Yeah I also found it strange when I was testing the plugin before publishing.

**Comment by swift-kim** [comment]
@bbrto21 I'm still getting an error when running the integration test on wearable 5.5 emulator.

```
Failure Details:
Failure in method: open app settings
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: <true>
  Actual: <false>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/swift/Git/plugins/packages/permission_handler/example/integration_test/permission_handler_test.dart:22:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/swift/Git/plugins/packages/permission_handler/example/integration_test/permission_handler_test.dart line 22
The test description was:
  open app settings
═════════════════════════════════════════════════════════════════

end of failure 1
```

**Comment by bbrto21** [comment]
> @bbrto21 I'm still getting an error when running the integration test on wearable 5.5 emulator.
> 
> ```
> Failure Details:
> Failure in method: open app settings
> ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
> The following TestFailure object was thrown running a test:
>   Expected: <true>
>   Actual: <false>
> 
> When the exception was thrown, this was the stack:
> #4      main.<anonymous closure> (file:///home/swift/Git/plugins/packages/permission_handler/example/integration_test/permission_handler_test.dart:22:5)
> <asynchronous suspension>
> <asynchronous suspension>
> (elided one frame from package:stack_trace)
> 
> This was caught by the test expectation on the following line:
>   file:///home/swift/Git/plugins/packages/permission_handler/example/integration_test/permission_handler_test.dart line 22
> The test description was:
>   open app settings
> ═════════════════════════════════════════════════════════════════
> 
> end of failure 1
> ```

According to my investigation, the setting app on tw3 and on wearable emulator are not ready for a launch operation of app control. Therefore, at least in Tizen 6.0 or in lower, this function cannot be used.(I've asked to review this issue.)
But on the other hand, I found that instead of showing the system settings, the app can show the own permissions view on Galaxy watch. please see this [PR](https://github.com/flutter-tizen/plugins/pull/142).
